version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - /Users/jacobo0312/Desktop/QUANTIL/ENV/front.env.js:/var/www/app/config/front.env.js 
    ports:
      - "3000:80"